---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nz16mpls5ebf/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets/css/main.css $DEPLOYPATH/assets/css
    - /bin/cp -R assets/img $DEPLOYPATH/assets
    - /bin/cp -R assets/js $DEPLOYPATH/assets
    - /bin/cp -R assets/scss $DEPLOYPATH/assets
    - /bin/cp -R assets/vendor $DEPLOYPATH/assets
    - /bin/cp -R forms $DEPLOYPATH