---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nz16mpls5ebf/public_html/
    - cp index.html $DEPLOYPATH
    - cp assets/css/main.css $DEPLOYPATH/assets/css
    - cp -R assets/img $DEPLOYPATH/assets
    - cp -R assets/js $DEPLOYPATH/assets
    - cp -R assets/scss $DEPLOYPATH/assets
    - cp -R assets/vendor $DEPLOYPATH/assets
    - cp -R forms $DEPLOYPATH